const ID_COMPANY = import.meta.env.VITE_ID_COMPANY;

export const PATH = {
    //sign_up
    sign_up_web: '/front/login',
    sign_up_zalo: '/front/sign-up-zalo',
    //user
    update_user_zalo: '/front/profile',

    //category
    get_all_categories: `/front/categories/${ID_COMPANY}`,

    //warehouse
    get_warehouses: `/warehouses?filters=company_id%20eq%20"${ID_COMPANY}"`,

    //product
    get_all_products: `/products?fields=id,xid,name,product_type,ratings:user{name,profile_image_url},ratings{rating,created_at,user_comment,shop_comment},slug,deposit,barcode_symbology,item_code,video,video_url,image,image_url,place_id,x_place_id,place{id,xid,title},category_id,x_category_id,category{id,xid,name},brand_id,x_brand_id,brand{id,xid,name},unit_id,x_unit_id,unit{id,xid,name,short_name},description,details{stock_quantitiy_alert,opening_stock,opening_stock_date,wholesale_price,wholesale_quantity,mrp,purchase_price,sales_price,tax_id,x_tax_id,purchase_tax_type,sales_tax_type,current_stock,warehouse_id,x_warehouse_id,status},details:tax{id,xid,name,rate},details:warehouse{id,xid,name},customFields{id,xid,field_name,field_value},warehouse_id,x_warehouse_id,warehouse{id,xid},parent_id,x_parent_id,variations.limit(10000).offset(0){id,xid,name,slug,item_code,product_type,barcode_symbology,item_code,video,video_url,image,image_url,category_id,x_parent_id,x_category_id,unit_id,x_unit_id,brand_id,x_brand_id},variations:productVariations{id,xid,product_id,x_product_id,variant_id,x_variant_id,variant_value_id,x_variant_value_id},variations:category{id,xid,name},variations:brand{id,xid,name},variations:unit{id,xid,name,short_name},variations:productVariations:variation{id,xid,name},variations:productVariations:variationType{id,xid,name},variations:details{stock_quantitiy_alert,opening_stock,opening_stock_date,wholesale_price,wholesale_quantity,mrp,purchase_price,sales_price,tax_id,x_tax_id,purchase_tax_type,sales_tax_type,current_stock,warehouse_id,x_warehouse_id,status},variations:details:tax{id,xid,name,rate},variations:details:warehouse{id,xid,name}&order=id%20desc&offset=0&limit=1000&warehouse=`,
    get_products_by_page: `/products?fields=id,xid,name,product_type,ratings:user{name,profile_image_url},ratings{rating,created_at,user_comment,shop_comment},slug,deposit,barcode_symbology,item_code,video,video_url,image,image_url,place_id,x_place_id,place{id,xid,title},category_id,x_category_id,category{id,xid,name},brand_id,x_brand_id,brand{id,xid,name},unit_id,x_unit_id,unit{id,xid,name,short_name},description,details{stock_quantitiy_alert,opening_stock,opening_stock_date,wholesale_price,wholesale_quantity,mrp,purchase_price,sales_price,tax_id,x_tax_id,purchase_tax_type,sales_tax_type,current_stock,warehouse_id,x_warehouse_id,status},details:tax{id,xid,name,rate},details:warehouse{id,xid,name},customFields{id,xid,field_name,field_value},warehouse_id,x_warehouse_id,warehouse{id,xid},parent_id,x_parent_id,variations.limit(10000).offset(0){id,xid,name,slug,item_code,product_type,barcode_symbology,item_code,video,video_url,image,image_url,category_id,x_parent_id,x_category_id,unit_id,x_unit_id,brand_id,x_brand_id},variations:productVariations{id,xid,product_id,x_product_id,variant_id,x_variant_id,variant_value_id,x_variant_value_id},variations:category{id,xid,name},variations:brand{id,xid,name},variations:unit{id,xid,name,short_name},variations:productVariations:variation{id,xid,name},variations:productVariations:variationType{id,xid,name},variations:details{stock_quantitiy_alert,opening_stock,opening_stock_date,wholesale_price,wholesale_quantity,mrp,purchase_price,sales_price,tax_id,x_tax_id,purchase_tax_type,sales_tax_type,current_stock,warehouse_id,x_warehouse_id,status},variations:details:tax{id,xid,name,rate},variations:details:warehouse{id,xid,name}&order=id%20desc`,
}